/** Static character map for popular Gutenberg books (by book ID). */
export const BOOK_CHARACTERS: Record<string, string[]> = {
  "84":    ["Victor Frankenstein", "The Creature", "Elizabeth Lavenza", "Henry Clerval", "Robert Walton"],
  "2701":  ["Captain Ahab", "Ishmael", "Queequeg", "Starbuck", "Stubb"],
  "1342":  ["Elizabeth Bennet", "Mr. Darcy", "Jane Bennet", "Mr. Bingley", "Lydia Bennet"],
  "1513":  ["Romeo", "Juliet", "Mercutio", "Tybalt", "Nurse"],
  "100":   ["Hamlet", "Othello", "Macbeth", "Prospero", "Puck"],
  "2641":  ["Lucy Honeychurch", "George Emerson", "Cecil Vyse", "Charlotte Bartlett", "Mr. Beebe"],
  "145":   ["Dorothea Brooke", "Tertius Lydgate", "Rosamond Vincy", "Will Ladislaw", "Nicholas Bulstrode"],
  "43":    ["Dr. Jekyll", "Mr. Hyde", "Mr. Utterson", "Dr. Lanyon", "Mr. Enfield"],
  "11":    ["Alice", "The Queen of Hearts", "The Mad Hatter", "The Cheshire Cat", "The White Rabbit"],
  "2554":  ["Raskolnikov", "Sonya Marmeladova", "Porfiry Petrovich", "Dunya Raskolnikova", "Svidrigailov"],
  "37106": ["Jo March", "Meg March", "Beth March", "Amy March", "Laurie"],
  "1260":  ["Jane Eyre", "Mr. Rochester", "St. John Rivers", "Mrs. Reed", "Adèle Varens"],
  "67979": ["Valancy Stirling", "Barney Snaith", "Olive Stirling", "Cissy Gay", "Mrs. Frederick"],
  "16328": ["Beowulf", "Hrothgar", "Grendel", "Wiglaf", "Unferth"],
  "16389": ["Lottie Wilkins", "Rose Arbuthnot", "Mrs. Fisher", "Lady Caroline Dester", "Mr. Briggs"],
  "768":   ["Heathcliff", "Catherine Earnshaw", "Edgar Linton", "Nelly Dean", "Isabella Linton"],
  "6761":  ["Ferdinand Fathom", "Renaldo de Melvil", "Monimia", "Elinor", "Celinda"],
  "394":   ["Mary Smith", "Miss Matty", "Miss Deborah", "Captain Brown", "Mrs. Jamieson"],
  "2160":  ["Humphry Clinker", "Matthew Bramble", "Lydia Melford", "Tabitha Bramble", "Winifred Jenkins"],
  "5197":  ["Richard Wagner", "Minna Planer", "Franz Liszt", "King Ludwig", "Hans von Bülow"],
  "1259":  ["D'Artagnan", "Athos", "Porthos", "Aramis", "Mazarin"],
  "4085":  ["Roderick Random", "Strap", "Narcissa", "Captain Oakum", "Miss Williams"],
  "6593":  ["Tom Jones", "Sophia Western", "Squire Allworthy", "Blifil", "Lady Bellaston"],
  "8492":  ["Hildred Castaigne", "Louis Castaigne", "Camilla", "Cassilda", "Mr. Wilde"],
  "1184":  ["Edmond Dantès", "Fernand Mondego", "Abbé Faria", "Mercédès", "Villefort"],
};
