/** Static description map for popular Gutenberg books (by book ID). */
export const BOOK_DESCRIPTIONS: Record<string, string> = {
  "84":    "A young scientist creates a sapient creature in an unorthodox experiment, then grapples with the consequences of playing god as his creation seeks revenge.",
  "2701":  "A sailor joins the crew of the Pequod, captained by the monomaniacal Ahab, who is obsessed with hunting the great white whale that took his leg.",
  "1342":  "In Regency England, the witty Elizabeth Bennet navigates society, family pressure, and her own misjudgments as she clashes with the proud Mr. Darcy.",
  "1513":  "Two teenagers fall in love. Their families have been killing each other for generations. It does not end well.",
  "100":   "The collected plays and poems of William Shakespeare, spanning comedies, tragedies, and histories that have shaped English literature for over four centuries.",
  "2641":  "A young Englishwoman travels to Florence, where a chance encounter challenges the rigid conventions of Edwardian society and awakens her to passion and freedom.",
  "145":   "In a provincial English town, the lives of an idealistic young woman and an ambitious doctor intertwine as they each discover that marriage and ambition rarely go as planned.",
  "43":    "A respected London doctor experiments with a potion that separates his good and evil natures, unleashing a terrifying alter ego he cannot control.",
  "11":    "A curious girl falls down a rabbit hole into a fantastical world where nothing makes sense, encountering mad tea parties, tyrannical queens, and talking animals.",
  "2554":  "A destitute former student in St. Petersburg commits murder, believing himself above moral law, then spirals into psychological torment as guilt consumes him.",
  "37106": "Four sisters come of age in Civil War-era New England, navigating poverty, ambition, love, and loss while their father serves as a Union chaplain.",
  "1260":  "An orphaned governess falls in love with her brooding employer, only to discover a devastating secret that forces her to choose between passion and principle.",
  "67979": "A timid, unloved woman receives a terminal diagnosis and decides to finally live on her own terms, defying her controlling family and finding unexpected love.",
  "16328": "A mighty warrior travels to Denmark to slay the monster Grendel, then faces Grendel's vengeful mother and, decades later, a fearsome dragon in his homeland.",
  "16389": "Four mismatched Englishwomen escape their dreary lives by renting an Italian castle for a month, where the Mediterranean sun transforms them in unexpected ways.",
  "768":   "On the wild Yorkshire moors, the passionate and destructive love between Heathcliff and Catherine Earnshaw consumes two families across generations.",
  "6761":  "A cunning adventurer schemes his way through eighteenth-century Europe, deceiving and betraying everyone around him in pursuit of wealth and status.",
  "394":   "The genteel ladies of a small English village navigate social upheaval, financial hardship, and quiet dramas with dignity, humor, and fierce loyalty to one another.",
  "2160":  "An eccentric Welsh squire and his entourage tour Britain, recounting their misadventures through a series of wildly contradictory and comic letters.",
  "5197":  "The controversial composer recounts his turbulent life — artistic triumphs, political exile, scandalous love affairs, and the relentless pursuit of his operatic vision.",
  "1259":  "D'Artagnan and the three musketeers reunite during the French civil wars, navigating palace intrigue, daring rescues, and shifting loyalties in a fractured kingdom.",
  "4085":  "A hot-tempered young Scotsman endures a picaresque series of misfortunes — poverty, naval service, and romantic disasters — as he fights his way through Georgian society.",
  "6593":  "A charming foundling raised by a country squire is cast out and embarks on a rollicking journey through eighteenth-century England, chasing love and dodging scandal.",
  "8492":  "A collection of interconnected tales haunted by a forbidden play that drives its readers to madness, blending gothic horror with decadent fin-de-siècle atmosphere.",
  "1184":  "A wrongfully imprisoned sailor escapes after fourteen years, reinvents himself as a wealthy count, and orchestrates an elaborate revenge against those who betrayed him.",
};
