/** Book-specific "rewrite" suggestion pills for the Build World tab (by Gutenberg book ID). */
export const BOOK_REWRITES: Record<string, string[]> = {
  "84": [
    "The Creature Writes A Memoir",
    "Victor Goes To Therapy",
    "Set The Whole Thing In Space",
    "The Creature Opens A Bakery",
    "Frankenstein But Make It A Romcom",
    "Victor Never Finishes The Experiment",
  ],
  "2701": [
    "Ahab And The Whale Become Friends",
    "Ishmael Starts A Podcast",
    "The Pequod Is A Cruise Ship",
    "Moby Dick But Underwater City",
    "Starbuck Leads A Mutiny",
    "The Whale Tells Its Side",
  ],
  "1342": [
    "Darcy Is A Tech Billionaire",
    "Elizabeth Starts A Book Club",
    "Wickham Runs For Parliament",
    "The Bennets Win The Lottery",
    "Set In Modern New York",
    "Mr Collins Becomes A Life Coach",
  ],
  "1513": [
    "Juliet Is Tech Genius Princess",
    "Benvolio Wants Everyone To Chill",
    "Big Mask Party In Space",
    "Fake Death Using Sleep Tech",
    "Romeo Runs Illegal Street Races",
    "Friar Plans Fake Viral Death",
  ],
  "100": [
    "All The Characters Meet In One Play",
    "Hamlet Gets A Therapist",
    "Puck Runs A Reality Show",
    "Every Comedy Ends Tragically",
    "Shakespeare Characters In High School",
    "The Histories But As A Heist",
  ],
  "2641": [
    "Lucy Stays In Florence Forever",
    "George Becomes A Painter",
    "Cecil Discovers Jazz Music",
    "Set In 1960s Florence",
    "The Pension Becomes A Commune",
    "Mr Emerson Writes A Philosophy Book",
  ],
  "145": [
    "Dorothea Opens A Free Clinic",
    "Lydgate Invents Modern Medicine",
    "Rosamond Becomes An Actress",
    "Casaubon Finishes His Book",
    "Set In Industrial Revolution London",
    "Fred Vincy Starts A Band",
  ],
  "43": [
    "Hyde Opens A Night Club",
    "Jekyll And Hyde Switch Places",
    "The Potion Goes Viral",
    "Utterson Solves It As A Detective",
    "Set In Modern Biotech Lab",
    "Hyde Becomes The Good One",
  ],
  "11": [
    "Alice Stays In Wonderland",
    "The Queen Of Hearts Reforms",
    "Cheshire Cat Tells The Story",
    "Wonderland Has WiFi",
    "Alice Returns As An Adult",
    "The Mad Hatter Opens A Cafe",
  ],
  "2554": [
    "Raskolnikov Starts A True Crime Podcast",
    "Sonya Becomes A Lawyer",
    "The Detective Is Actually Wrong",
    "Set In Modern Moscow",
    "Raskolnikov Confesses Immediately",
    "The Landlady Solves Everything",
  ],
  "37106": [
    "Jo March Goes To Hollywood",
    "Beth Survives And Becomes A Pianist",
    "Amy Opens An Art Gallery In Paris",
    "Meg Starts A School",
    "Set During World War II",
    "Laurie And Jo End Up Together",
  ],
  "1260": [
    "Bertha Tells Her Side",
    "Jane Inherits Rochester's Estate",
    "Set In Modern Boarding School",
    "Rochester Is Actually Nice",
    "Jane Becomes A Famous Author",
    "The Red Room Is A Portal",
  ],
  "67979": [
    "Luisa Fakes Her Death Instead",
    "The Family Discovers Her Plan",
    "Set In A Small Beach Town",
    "Luisa Starts A Secret Business",
    "Everyone Gets Their Own Diagnosis",
    "Luisa Lives And Tells Them Off",
  ],
  "16328": [
    "Grendel Is Misunderstood",
    "Beowulf Loses The First Fight",
    "The Dragon Guards A Secret",
    "Set In A Viking Sci-Fi World",
    "Grendel's Mother Gets Revenge",
    "Beowulf Retires After Grendel",
  ],
  "16389": [
    "The Castle Is Haunted",
    "They Never Leave Italy",
    "One Of Them Falls For A Local",
    "Set In A Modern Villa Rental",
    "The Rain Never Stops",
    "They Buy The Castle Together",
  ],
  "768": [
    "Heathcliff And Catherine Communicate",
    "Nelly Dean Writes A Tell-All",
    "Set In Modern Yorkshire",
    "Heathcliff Never Leaves",
    "Catherine Chooses The Moors",
    "The Next Generation Breaks The Cycle",
  ],
  "6761": [
    "Barry Lyndon Gets Caught Early",
    "His Son Takes Over The Scheme",
    "Set In Modern Wall Street",
    "Lady Lyndon Fights Back",
    "Barry Becomes A Spy",
    "The Narrator Is Unreliable",
  ],
  "394": [
    "Cranford Gets A Railway Station",
    "Miss Matty Opens A Tea Empire",
    "Captain Brown Survives",
    "Set In A Modern Small Town",
    "The Ladies Start A Newspaper",
    "A Scandal Rocks The Village",
  ],
  "2160": [
    "The Letters Are All Lies",
    "Bramble Goes To America Instead",
    "Lismahago Starts A Revolution",
    "Set As A Modern Road Trip",
    "Win Jenkins Tells The Real Story",
    "They Never Make It Home",
  ],
  "5197": [
    "Wagner Gives Up Music",
    "Ludwig Cuts The Funding",
    "Cosima Writes The Operas",
    "Set In Modern Music Industry",
    "Wagner Meets His Rivals",
    "The Ring Cycle Is A Video Game",
  ],
  "1259": [
    "D'Artagnan Switches Sides",
    "Milady Returns From The Dead",
    "The Musketeers Open A Tavern",
    "Set During The French Revolution",
    "Mazarin Has A Secret Twin",
    "Porthos Becomes King",
  ],
  "4085": [
    "Roderick Stays In Scotland",
    "Strap Becomes The Hero",
    "Narcissa Saves Herself",
    "Set In Colonial America",
    "Roderick Joins The Navy Properly",
    "The Uncle Was Right All Along",
  ],
  "6593": [
    "Tom Jones Discovers His Parents Early",
    "Sophia Western Runs Away First",
    "Blifil Gets What He Deserves",
    "Set In Victorian London",
    "Squire Allworthy Investigates",
    "Tom Becomes A Magistrate",
  ],
  "8492": [
    "Someone Finishes Reading The Play",
    "The Yellow Sign Spreads Online",
    "Carcosa Is A Real Place",
    "Set In Modern New York",
    "The King In Yellow Is A Podcast",
    "Mr Wilde Escapes The Asylum",
  ],
  "1184": [
    "Dantès Forgives Everyone",
    "Mercedes Helps Him Escape",
    "The Treasure Is Cursed",
    "Set In Modern Monte Carlo",
    "Villefort Confesses Early",
    "Dantès Builds An Empire Instead",
  ],
};
