import type { RewriteData } from "./types";

/** Community rewrites with full data (character, story input) — used by sidebar + EndBookScreen. */
export const COMMUNITY_REWRITES: Record<string, RewriteData[]> = {
  "84": [
    { premise: "The Creature writes a memoir about learning what it means to be human.", characterName: "The Creature", storyInput: "text" },
    { premise: "Victor checks into a sanatorium and confronts his obsession.", characterName: "Victor Frankenstein", storyInput: "taptale" },
    { premise: "Set aboard a deep-space research vessel where the experiment goes wrong.", characterName: "Robert Walton", storyInput: "cardtale" },
    { premise: "The Creature opens a bakery in a small village and tries to fit in.", characterName: "The Creature", storyInput: "taptale" },
  ],
  "2701": [
    { premise: "Ahab and the white whale form an unlikely alliance against whalers.", characterName: "Captain Ahab", storyInput: "text" },
    { premise: "Ishmael starts a podcast documenting life aboard the Pequod.", characterName: "Ishmael", storyInput: "taptale" },
    { premise: "The Pequod becomes a luxury cruise ship with a dark secret below deck.", characterName: "Starbuck", storyInput: "cardtale" },
    { premise: "The whale tells the story from beneath the waves.", characterName: "Ishmael", storyInput: "text" },
  ],
  "1342": [
    { premise: "Darcy is a tech billionaire and Elizabeth is a journalist investigating him.", characterName: "Elizabeth Bennet", storyInput: "text" },
    { premise: "Elizabeth starts a book club that accidentally changes Meryton forever.", characterName: "Elizabeth Bennet", storyInput: "taptale" },
    { premise: "Wickham runs for Parliament and Darcy has to stop him.", characterName: "Mr. Darcy", storyInput: "cardtale" },
    { premise: "The Bennets win the lottery and chaos ensues.", characterName: "Lydia Bennet", storyInput: "taptale" },
  ],
  "1513": [
    { premise: "Juliet is a tech genius princess who hacks the family feud.", characterName: "Juliet", storyInput: "text" },
    { premise: "A massive masquerade in zero gravity where nobody knows who's who.", characterName: "Romeo", storyInput: "cardtale" },
    { premise: "Fake death using experimental sleep technology goes sideways.", characterName: "Juliet", storyInput: "taptale" },
    { premise: "Benvolio tries desperately to get everyone to calm down.", characterName: "Mercutio", storyInput: "taptale" },
  ],
  "11": [
    { premise: "Alice decides to stay in Wonderland and build a life there.", characterName: "Alice", storyInput: "text" },
    { premise: "The Queen of Hearts has a change of heart and reforms Wonderland.", characterName: "The Queen of Hearts", storyInput: "taptale" },
    { premise: "The Cheshire Cat narrates the story from the shadows.", characterName: "The Cheshire Cat", storyInput: "cardtale" },
    { premise: "The Mad Hatter opens a cafe and all of Wonderland comes for tea.", characterName: "The Mad Hatter", storyInput: "taptale" },
  ],
  "1260": [
    { premise: "Bertha Mason finally tells her own story.", characterName: "Jane Eyre", storyInput: "text" },
    { premise: "Jane inherits Rochester's estate and runs it her own way.", characterName: "Jane Eyre", storyInput: "taptale" },
    { premise: "Set in a modern boarding school with dark secrets.", characterName: "Jane Eyre", storyInput: "cardtale" },
  ],
  "2554": [
    { premise: "Raskolnikov starts a true crime podcast about his own case.", characterName: "Raskolnikov", storyInput: "text" },
    { premise: "Sonya becomes a defense lawyer and takes on impossible cases.", characterName: "Sonya Marmeladova", storyInput: "taptale" },
    { premise: "The detective is actually wrong about everything.", characterName: "Porfiry Petrovich", storyInput: "cardtale" },
  ],
  "37106": [
    { premise: "Jo March goes to Hollywood to write screenplays.", characterName: "Jo March", storyInput: "text" },
    { premise: "Beth survives her illness and becomes a concert pianist.", characterName: "Beth March", storyInput: "taptale" },
    { premise: "Amy opens an art gallery in Paris and the family visits.", characterName: "Amy March", storyInput: "cardtale" },
  ],
};

/** Book-specific "rewrite" suggestion pills for the Build World tab (by Gutenberg book ID). */
export const BOOK_REWRITES: Record<string, string[]> = {
  "84": [
    "The Creature Writes A Memoir",
    "Victor Goes To Therapy",
    "Set The Whole Thing In Space",
    "The Creature Opens A Bakery",
    "Frankenstein But Make It A Romcom",
    "Victor Never Finishes The Experiment",
  ],
  "2701": [
    "Ahab And The Whale Become Friends",
    "Ishmael Starts A Podcast",
    "The Pequod Is A Cruise Ship",
    "Moby Dick But Underwater City",
    "Starbuck Leads A Mutiny",
    "The Whale Tells Its Side",
  ],
  "1342": [
    "Darcy Is A Tech Billionaire",
    "Elizabeth Starts A Book Club",
    "Wickham Runs For Parliament",
    "The Bennets Win The Lottery",
    "Set In Modern New York",
    "Mr Collins Becomes A Life Coach",
  ],
  "1513": [
    "Juliet Is Tech Genius Princess",
    "Benvolio Wants Everyone To Chill",
    "Big Mask Party In Space",
    "Fake Death Using Sleep Tech",
    "Romeo Runs Illegal Street Races",
    "Friar Plans Fake Viral Death",
  ],
  "100": [
    "All The Characters Meet In One Play",
    "Hamlet Gets A Therapist",
    "Puck Runs A Reality Show",
    "Every Comedy Ends Tragically",
    "Shakespeare Characters In High School",
    "The Histories But As A Heist",
  ],
  "2641": [
    "Lucy Stays In Florence Forever",
    "George Becomes A Painter",
    "Cecil Discovers Jazz Music",
    "Set In 1960s Florence",
    "The Pension Becomes A Commune",
    "Mr Emerson Writes A Philosophy Book",
  ],
  "145": [
    "Dorothea Opens A Free Clinic",
    "Lydgate Invents Modern Medicine",
    "Rosamond Becomes An Actress",
    "Casaubon Finishes His Book",
    "Set In Industrial Revolution London",
    "Fred Vincy Starts A Band",
  ],
  "43": [
    "Hyde Opens A Night Club",
    "Jekyll And Hyde Switch Places",
    "The Potion Goes Viral",
    "Utterson Solves It As A Detective",
    "Set In Modern Biotech Lab",
    "Hyde Becomes The Good One",
  ],
  "11": [
    "Alice Stays In Wonderland",
    "The Queen Of Hearts Reforms",
    "Cheshire Cat Tells The Story",
    "Wonderland Has WiFi",
    "Alice Returns As An Adult",
    "The Mad Hatter Opens A Cafe",
  ],
  "2554": [
    "Raskolnikov Starts A True Crime Podcast",
    "Sonya Becomes A Lawyer",
    "The Detective Is Actually Wrong",
    "Set In Modern Moscow",
    "Raskolnikov Confesses Immediately",
    "The Landlady Solves Everything",
  ],
  "37106": [
    "Jo March Goes To Hollywood",
    "Beth Survives And Becomes A Pianist",
    "Amy Opens An Art Gallery In Paris",
    "Meg Starts A School",
    "Set During World War II",
    "Laurie And Jo End Up Together",
  ],
  "1260": [
    "Bertha Tells Her Side",
    "Jane Inherits Rochester's Estate",
    "Set In Modern Boarding School",
    "Rochester Is Actually Nice",
    "Jane Becomes A Famous Author",
    "The Red Room Is A Portal",
  ],
  "67979": [
    "Luisa Fakes Her Death Instead",
    "The Family Discovers Her Plan",
    "Set In A Small Beach Town",
    "Luisa Starts A Secret Business",
    "Everyone Gets Their Own Diagnosis",
    "Luisa Lives And Tells Them Off",
  ],
  "16328": [
    "Grendel Is Misunderstood",
    "Beowulf Loses The First Fight",
    "The Dragon Guards A Secret",
    "Set In A Viking Sci-Fi World",
    "Grendel's Mother Gets Revenge",
    "Beowulf Retires After Grendel",
  ],
  "16389": [
    "The Castle Is Haunted",
    "They Never Leave Italy",
    "One Of Them Falls For A Local",
    "Set In A Modern Villa Rental",
    "The Rain Never Stops",
    "They Buy The Castle Together",
  ],
  "768": [
    "Heathcliff And Catherine Communicate",
    "Nelly Dean Writes A Tell-All",
    "Set In Modern Yorkshire",
    "Heathcliff Never Leaves",
    "Catherine Chooses The Moors",
    "The Next Generation Breaks The Cycle",
  ],
  "6761": [
    "Barry Lyndon Gets Caught Early",
    "His Son Takes Over The Scheme",
    "Set In Modern Wall Street",
    "Lady Lyndon Fights Back",
    "Barry Becomes A Spy",
    "The Narrator Is Unreliable",
  ],
  "394": [
    "Cranford Gets A Railway Station",
    "Miss Matty Opens A Tea Empire",
    "Captain Brown Survives",
    "Set In A Modern Small Town",
    "The Ladies Start A Newspaper",
    "A Scandal Rocks The Village",
  ],
  "2160": [
    "The Letters Are All Lies",
    "Bramble Goes To America Instead",
    "Lismahago Starts A Revolution",
    "Set As A Modern Road Trip",
    "Win Jenkins Tells The Real Story",
    "They Never Make It Home",
  ],
  "5197": [
    "Wagner Gives Up Music",
    "Ludwig Cuts The Funding",
    "Cosima Writes The Operas",
    "Set In Modern Music Industry",
    "Wagner Meets His Rivals",
    "The Ring Cycle Is A Video Game",
  ],
  "1259": [
    "D'Artagnan Switches Sides",
    "Milady Returns From The Dead",
    "The Musketeers Open A Tavern",
    "Set During The French Revolution",
    "Mazarin Has A Secret Twin",
    "Porthos Becomes King",
  ],
  "4085": [
    "Roderick Stays In Scotland",
    "Strap Becomes The Hero",
    "Narcissa Saves Herself",
    "Set In Colonial America",
    "Roderick Joins The Navy Properly",
    "The Uncle Was Right All Along",
  ],
  "6593": [
    "Tom Jones Discovers His Parents Early",
    "Sophia Western Runs Away First",
    "Blifil Gets What He Deserves",
    "Set In Victorian London",
    "Squire Allworthy Investigates",
    "Tom Becomes A Magistrate",
  ],
  "8492": [
    "Someone Finishes Reading The Play",
    "The Yellow Sign Spreads Online",
    "Carcosa Is A Real Place",
    "Set In Modern New York",
    "The King In Yellow Is A Podcast",
    "Mr Wilde Escapes The Asylum",
  ],
  "1184": [
    "Dantès Forgives Everyone",
    "Mercedes Helps Him Escape",
    "The Treasure Is Cursed",
    "Set In Modern Monte Carlo",
    "Villefort Confesses Early",
    "Dantès Builds An Empire Instead",
  ],
};
